Feat: Banner Grid
deco-sites/bolovo-store pull request #19
Opened 2023-12-18 21:59 UTC by martinadam75

Adicionado componente Banner Grid igual demonstrado na imagem:

![image](https://github.com/deco-sites/bolovo-store/assets/84191864/40dce7ec-505b-4097-b0a9-e9e4db04ca25)

Pode ser selecionado a quantidade de itens por coluna tanto desktop quanto mobile além de todos os itens serem customizados.

2023-12-19 16:29 UTC, gustavo-adaptio requested changes

2023-12-19 16:29 UTC, gustavo-adaptio commented on components/content/BannerGrid.tsx
> +              />
A largura/altura deve seguir de forma dinamica de acordo com a largura da tela, exemplo:
Se no mobile (abaixo de 992, se nao me engano, siga o `lg`) vai aplicar 2 imagens, então precisamos que as duas imagens tenham pelo menos: ( 992 (largura da tela) / 2 (quantidade por linha) ) / 2  -> tem que dividir de novo por dois pq o script da Deco cria duas versoes, 1x e 2x. Logo ficam duas imagens que possuem larguras de 248 até 496.

Essa mesma logica deve se aplicar no desktop para monitores até 1920 (aproximadamente 992 * 2, o excedente é detalhe)

2023-12-19 16:29 UTC, gustavo-adaptio commented on components/content/BannerGrid.tsx
> +                sizes="(max-width: 523px) 100vw, 30vw"
esse sizes é dispensavel

2023-12-19 16:29 UTC, gustavo-adaptio commented on components/content/BannerGrid.tsx
> +                loading="lazy"
`loading`, `fetchPriority` e `preload` devem entrar como configuraçoes *da section* (nao da imagem)

2023-12-19 16:29 UTC, gustavo-adaptio commented on components/content/BannerGrid.tsx
> +          }
Voce consegue aplicar essas regras todas pelo tailwind:

absolute bottom-0 left-0 (right e top 0 sao dispensaveis, so dois valores X e Y sao suficientes) bg-white flex items-center justify-center overflow-hidden transition-['height, opacity'] duration-3 (se n me engano)

As classes que criou abaixo voce tambem consegue usar com tailwind.

Essa forma que usou nao é legal pq impede o layout de ser carregado de uma vez, o navegador olha um CSS (do tailwind) pinta a tela e depois olha mais esse style e pinta de novo. De qualquer forma, use o padrao de desenvolvimento do tailwind para tudo para nao reinventarmos a roda. Se precisar de ajuda me avise.

2023-12-20 16:09 UTC, martinadam75 commented
Enviado commit com as alterações solicitadas

2023-12-26 19:10 UTC, merged