feat: add menu shops
deco-sites/bolovo-store pull request #2
Opened 2023-11-02 15:41 UTC by devartes

![image](https://github.com/deco-sites/bolovo-store/assets/76822093/e5ae1240-6578-41be-b264-ca7dfe67b2e0)

2023-11-07 15:20 UTC, gustavo-adaptio requested changes

2023-11-07 15:20 UTC, gustavo-adaptio commented on components/header/Menu.tsx
> +            <MenuItem item={menu} />
Acredito que nao exista nenhum caso onde `item` nao é um array. Se tiver, voce deve criar a tipagem correspondente pois `{ item: NavItemProps[] }` diz que `item` é um array 

#dica: Prefira inves de "item" usar "items", o plural ajuda a identificar no meio do codigo o que as coisas sao.

2023-11-07 15:20 UTC, gustavo-adaptio commented on components/header/NavItem.tsx
> +            class={`text-base ${isChild ? 'font-normal' : 'font-semibold'} leading-9 whitespace-nowrap`}
Tudo que retorna um JSX é um componente, logo `renderLinks` é um componente e por isso deveria ser `RenderLinks` ou só `Links`. Mesma logica para o `renderImages`.

2023-11-07 15:20 UTC, gustavo-adaptio commented on components/header/NavItem.tsx
> +        </figure>
A imagem pode ser menor, tente usar metade do que realmente necessario pois o script da Deco vai pegar esses 242px e criar uma imagem 2x maior, de 484px, o que nao vamos usar/aproveitar nem em uma tela de 2500px. 
Pense nesse logica sempre que usar imagens, assim conseguimos ter um uso muito mais otimizado delas ;)


off: adorei o uso de figure e figcaption, muito bem 👏

2023-11-09 11:08 UTC, devartes commented on components/header/Menu.tsx
> +            <MenuItem item={menu} />
Aqui

![image](https://github.com/deco-sites/bolovo-store/assets/76822093/4de07084-d2cc-46bb-8b53-c2cc319d75fa)

2023-11-09 11:10 UTC, devartes commented on components/header/NavItem.tsx
> +            class={`text-base ${isChild ? 'font-normal' : 'font-semibold'} leading-9 whitespace-nowrap`}
Feito
![image](https://github.com/deco-sites/bolovo-store/assets/76822093/aba532ca-92c7-492c-b771-36b5911123e0)
![image](https://github.com/deco-sites/bolovo-store/assets/76822093/43cc0f4a-91ba-4729-82ea-3b14883f754b)

2023-11-09 11:12 UTC, devartes commented on components/header/NavItem.tsx
> +        </figure>
Eu testei com 121 de width e height , mas ficou muito pequeno , mantive o 242 e usei uma % pra ele reduzir conforme reduz a tela e removi a quebra nas imagens quando reduzia a tela.
![image](https://github.com/deco-sites/bolovo-store/assets/76822093/0522c956-0761-4d59-b205-96ab0b5d1dcd)

2023-11-13 23:48 UTC, gustavo-adaptio commented on components/header/NavItem.tsx
> +        </figure>
A imagem vai diminuir de tamanho mesmo, mas ai voce coloca o tamanho real via classes como `w-full` por exemplo. Inclusive esse 80.65% n é legal, prefira arredondar, geralmente esses pontos decimais nao fazem diferença real `w-4/5`

2023-11-13 23:49 UTC, gustavo-adaptio commented on components/header/Menu.tsx
> +            <MenuItem item={menu} />
Nao entendi.

2023-11-14 10:21 UTC, devartes commented on components/header/Menu.tsx
> +            <MenuItem item={menu} />
> Acredito que nao exista nenhum caso onde `item` nao é um array. Se tiver, voce deve criar a tipagem correspondente pois `{ item: NavItemProps[] }` diz que `item` é um array
> 
> #dica: Prefira inves de "item" usar "items", o plural ajuda a identificar no meio do codigo o que as coisas sao.

Troquei "item" por "items" como falaste acima

2023-11-14 10:36 UTC, devartes commented on components/header/NavItem.tsx
> +        </figure>
Feito
![image](https://github.com/deco-sites/bolovo-store/assets/76822093/13083d73-cc73-4a92-a3fe-babfd17be231)

2023-12-01 21:17 UTC, merged