Feat/product highlight
deco-sites/bolovo-store pull request #26
Opened 2023-12-27 20:03 UTC by ApMatheus

2023-12-27 21:08 UTC, gustavo-adaptio requested changes

2023-12-27 21:08 UTC, gustavo-adaptio commented on sections/Product/FeaturedGallery.tsx
> +    };
Substitua esses valores por valore semanticos que sejam facilmente entendiveis como: "imagem na direita" e "imagem na esquerda" (importante ter esse entendimento nas configuraçoes para que sejam faceis de serem configuradas.

2023-12-27 21:08 UTC, gustavo-adaptio commented on sections/Product/FeaturedGallery.tsx
> +    idProduct: Product[] | null;
Melhor usar apenas `product` para evitar erros de entendimento em manutençoes no futuro pois nao é um ID (string/number), e sim um objeto
```suggestion
    product: Product[] | null;
```

2023-12-27 21:08 UTC, gustavo-adaptio commented on sections/Product/FeaturedGallery.tsx
> +            <h3 class=" text-base text-left uppercase font-bold">
segue a ordem de heading: so chama h3 se voce ja chamou um h2 em um elemento pai
```suggestion
            <h2 class=" text-base text-left uppercase font-bold">
```

2023-12-27 21:08 UTC, gustavo-adaptio commented on sections/Product/FeaturedGallery.tsx
> +                <div class={`flex gap-2 lg:gap-4 ${MOBILE_DIRECTION[directionInverse?.mobile ?? "col-reverse"]
Voce nao rpecisa dessa div, poderia colocar essas classes na tag `a`

2023-12-27 21:08 UTC, gustavo-adaptio commented on sections/Product/FeaturedGallery.tsx
> +    directionInverse: {
facilitar as props
```suggestion
    contentDirection: {
```

2023-12-28 21:10 UTC, ApMatheus commented on sections/Product/FeaturedGallery.tsx
> +                <div class={`flex gap-2 lg:gap-4 ${MOBILE_DIRECTION[directionInverse?.mobile ?? "col-reverse"]
Gu quando eu removo a div a tag a renderiza de forma confusa, renderiza varias vezes e de forma errada, provocando até mesmo uma quebra, por isso mudei um pouco a estrutura 

![image](https://github.com/deco-sites/bolovo-store/assets/66977676/a8e16786-1ebd-478e-bf72-7272aaccf3c3)

2023-12-28 22:29 UTC, merged