Feat/search no result
deco-sites/bolovo-store pull request #30
Opened 2024-01-03 00:36 UTC by ApMatheus

2024-01-09 14:46 UTC, gustavo-mvp requested changes

2024-01-09 14:46 UTC, gustavo-mvp commented on components/ui/SearchedWord.tsx
> +
Nao faz sentido criar uma função e ja utilizar ela na linha debaixo dessa forma, voce poderia ter simplsmente colocado direto na variavel que precisa. Seria melhor se colocasse num useEffect ou coisa do tipo

2024-01-09 14:46 UTC, gustavo-mvp commented on components/ui/SearchedWord.tsx
> +    }
Nao tem necessidade desse componente ser uma ilha. O valor da querystring voce consegue pegar por um loader inline no SearchResult (a section).

Num loader inline voce tem o segundo parametro `req` e nele voce tem a URL da pagina, ainda no servidor, a partir disso voce consegue pegar o valor da querystring, ja tratar, e enviar para o componente apenas o texto do campo que voce precisa.

Referencia:
![image](https://github.com/deco-sites/bolovo-store/assets/155124851/0ef3586f-b33d-4747-a645-a06c2b861034)

2024-01-09 14:46 UTC, gustavo-mvp commented on components/search/NotFound.tsx
> +    stepsBySteps: RichText[];
Da onde ta vindo essa tipagem?

2024-01-09 14:46 UTC, gustavo-mvp commented on components/search/NotFound.tsx
> +        desktop: ImageWidget
tem que ser opcional
```suggestion
        mobile?: ImageWidget;
        desktop?: ImageWidget
```

2024-01-09 14:46 UTC, gustavo-mvp commented on components/search/NotFound.tsx
> +        src: ImageWidget;
tem que ser opcional
```suggestion
        src?: ImageWidget;
```

2024-01-09 14:46 UTC, gustavo-mvp commented on components/search/NotFound.tsx
> +            <div class={`${!imagem?.active && "mt-24"}`}>
Como a `Image` é a parte variante na tela, inves de colocar um margin top na div, coloca um margin bottom na imagem. Assim voce nao precisa tratar nada na div (nesse caso acho que voce nem precisa dessa div)

2024-01-09 14:46 UTC, gustavo-mvp commented on components/search/NotFound.tsx
> +            <p class={`uppercase font-bold text-center ${TEXT_COLOR[theme ?? "dark"]}`}>
esse TEXT_COLOR poderia fica no container do not found para evitar ter que ficar usando varias vezes (propriedades de texto pegam naturalmente do pai se nao tiver nenhum)

2024-01-09 14:46 UTC, gustavo-mvp commented on components/search/NotFound.tsx
> +                    <Picture preload={false}>
Como isso aparece na tela na primeira renderização, o preload precisa estar ativo, fetchPriority high e loading eager

2024-01-09 14:46 UTC, gustavo-mvp commented on components/search/NotFound.tsx
> +                        />
Acredito que apenas dois Source sejam o suficiente, 1024 ate 1500 e 1500 pra cima

2024-01-09 14:46 UTC, gustavo-mvp commented on components/search/NotFound.tsx
> +                            loading={"lazy"}
```suggestion
                            loading="eager"
```

2024-01-09 14:46 UTC, gustavo-mvp commented on components/search/NotFound.tsx
> +                <ProductShelf products={primaryShelf.products} title={primaryShelf.title} layout={primaryShelf.layout} cardLayout={primaryShelf.cardLayout} seeMore={primaryShelf.seeMore} />
Da pra fazer assim:
```suggestion
                <ProductShelf {...primaryShelf} />
```

2024-01-09 14:46 UTC, gustavo-mvp commented on components/search/NotFound.tsx
Nao entendi pq tem um condicional por causa do backgroundImage, nao seria melhor so fazer a renderização dele ou nao? afinal é um bloco absoluto que nao deveria interferir no resto do componente.

2024-01-09 14:46 UTC, gustavo-mvp commented on components/GlobalTags.tsx
> +        }
Fontes Google devem ser tratadas no Theme (configuraçao pelo Admin)
```suggestion
```

2024-01-11 11:43 UTC, MatheusApRocky commented on components/search/NotFound.tsx
> +            <div class={`${!imagem?.active && "mt-24"}`}>
Gu aqui é pra quando não tiver imagem acima, ai sim ele ativa esse margin-top,

2024-01-11 14:09 UTC, ApMatheus commented on components/search/NotFound.tsx
> +            <div class={`${!imagem?.active && "mt-24"}`}>
Gu aqui é pra quando não tiver imagem acima, ai sim ele ativa esse margin-top,

2024-01-11 23:02 UTC, merged