Feat: Category List
deco-sites/bolovo-store pull request #35
Opened 2024-01-16 21:48 UTC by martinadam75

2024-01-24 21:59 UTC, gustavo-mvp requested changes

2024-01-24 21:59 UTC, gustavo-mvp commented on components/PLP/CategoryResult.tsx
> +}
prop desnecessaria

2024-01-24 21:59 UTC, gustavo-mvp commented on components/PLP/CategoryResult.tsx
> +  page: ProductListingPage | null;
O que diz para uma tipagem que é um array é o `[]` entao nomear CategoryArray[] é ambiguo.
```suggestion
export interface Category {
  /** @description RegExp to enable this banner on the current URL. Use /feminino/* to display this banner on feminino category  */
  matcher: string;
  category: string;
  url: string
  /**
 * @description Subcategorias existentes
 */
  items?: { 
    label: string; 
    url: string
  }[]; 
}

export interface Props {
  /** @title Integration */
  categories: Category[];
  page: ProductListingPage | null;
```

2024-01-24 21:59 UTC, gustavo-mvp commented on sections/Product/SearchResult.tsx
Como voce criou o CategoryResult acho que isso nao precisa mais existir.

2024-01-24 21:59 UTC, gustavo-mvp commented on components/search/GalleryControls.tsx
> +                    href={!parentCategory ? `/` + currentCategory : `/` + parentCategory}
Nao monta a URL assim, da pra ver que esses resultados nao dao em nada na pagina que criou. É melhor deixar que o lojista configure a pagina que ele quer enviar os usuarios

2024-01-24 21:59 UTC, gustavo-mvp commented on components/search/GalleryControls.tsx
> +            <SliderJS rootId={id} />
Como nao tem botao nem dots, ce nao precisa do SliderJS aqui

2024-01-25 04:14 UTC, martinadam75 commented on sections/Product/SearchResult.tsx
Não entendi aqui @gustavo-mvp, acho que faltou você marcar exatamente o que não precisa mais existir.

2024-01-30 22:03 UTC, closed without merging