Feat/text plus video
deco-sites/bolovo-store pull request #7
Opened 2023-11-22 20:44 UTC by ApMatheus

2023-11-24 04:52 UTC, gustavo-adaptio requested changes

2023-11-24 04:52 UTC, gustavo-adaptio commented on components/GlobalTags.tsx
> +      },`,
Faça a conversao das fontes para os outros formatos que comentei no discord por favor - ttf, woff e woff2. Alem disso, adicione no font-face o `font-display: swap` para garantir que nao perderemos performance (https://desenvolvimentoparaweb.com/css/font-display-controle-de-exibicao-de-fontes-para-ajuste-em-performance/)

2023-11-24 04:52 UTC, gustavo-adaptio commented on components/GlobalTags.tsx
> +          @font-face {
Faça apenas uma tag `style` com todos os `font-face`

2023-11-24 04:52 UTC, gustavo-adaptio commented on sections/Content/TextPlusVideo.tsx
> +export default function TextPlusVideo({ directionInverse, image, textContent, listImages, videoLink }: Props) {
Muda o nome da Section para `VideoAndText`

2023-11-24 04:52 UTC, gustavo-adaptio commented on sections/Content/TextPlusVideo.tsx
> +    }[];
Sobre o comentario do Suzano do formulario, dessa forma o que o usuario colocar no `alt` será considerado o nome do item no admin
```suggestion
    listImages: {
        src: ImageWidget;
        /** @title Alt */
        label: string;
    }[];
```

2023-11-24 04:52 UTC, gustavo-adaptio commented on components/GlobalTags.tsx
> +            font-family: "AcuminPro-Regular";
Voce pode chamar todas as fontes de `Acumin` sem problemas, fica mais facil de codar tambem

2023-11-24 04:52 UTC, gustavo-adaptio commented on tailwind.config.ts
> +      },
Chamando todas pelo mesmo nome voce pode criar apenas uma chave `acumin` que renderiza apenas uma fonte. (prefir minusculo para seguir o padrao de classes do tailwind)

2023-11-24 04:54 UTC, gustavo-adaptio requested changes

2023-11-24 04:54 UTC, gustavo-adaptio commented on sections/Content/TextPlusVideo.tsx
> +                                    <Image src={img.src} alt={img.alt} width={100} height={37} loading={"eager"} class="max-w-[70px] xl:max-w-[100px] 2xl:max-w-[150px]" />
loading lazy aqui, tudo que estiver abaixo da linha de renderizaçao critica (o que voce ve quando a pagina carrega) deve ter loading=lazy
```suggestion
                                    <Image src={img.src} alt={img.alt} width={100} height={37} loading="lazy" class="max-w-[70px] xl:max-w-[100px] 2xl:max-w-[150px]" />
```

2023-11-24 04:54 UTC, gustavo-adaptio commented on sections/Content/TextPlusVideo.tsx
> +                        </iframe>
```suggestion
                        <iframe width="560" height="315" src={videoLink + "?si=n_vAKsEE_BMTv0jn"} title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                            class={"w-full h-full"}
                            allowfullscreen
                            loading="lazy" />
```

2023-11-26 12:09 UTC, ApMatheus commented on sections/Content/TextPlusVideo.tsx
> +                        </iframe>
Não entendi o comentario aqui Gu

2023-12-01 01:31 UTC, merged